### ISSUE TITLE
Homepage: Mack Truck Builder Form/CTA (MVP-static) Block

### ISSUE THREAD

**Issue by manuel-vara** [Netcentric/vg-macktrucks-com-rd#10]
![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/116451851/5e7d522d-87af-4483-a6ec-d1d116396093)
MVP = New Block using only one static image as shown in the screenshot. Future enhancements to make more interactive.

**Comment by Lakshmishri** [comment]
As decide in stand up we will use [V2 columns blocks]( https://github.com/Netcentric/vg-macktrucks-com-rd/issues/41 )for MVP
