### ISSUE TITLE
Bug - Minor - Trucks Lineup Carousel - The title is not aligned with the navigation tabs

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-macktrucks-com-rd#100]
On the Trucks Lineup Carousel, the title is not correctly aligned with the navigation tabs as according to the figma design

**Steps to reproduce:**
1. Open https://13-trucks-carousel--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/laura/
2. Open the figma design https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2220%3A92927&mode=dev 
3. Notice that the position of the Title is not aligned with the navigation tabs as on the design

**Expected result**
Title should be aligned with the navigation tabs like on the figma design

**Actual result**
Title is not aligned with the navigation tabs like on the figma design

<img width="1722" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/5206aad4-8537-40bd-b561-dcd331c841a2">

**Comment by Andrei-Boiangiu** [comment]
#13

**Comment by DanielaPedrochevd** [comment]
confirmed as bug

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
as tested on https://100-lineup-tabs--vg-macktrucks-com-rd--netcentric.hlx.page/homepage

<img width="1465" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/e8a3f65d-6cd3-420b-b137-632da15a38b7">
