### ISSUE TITLE
FR: MT "All Trucks" Filtering 

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#103]
**Agile Requirement**
As a business owner, I want the "All Trucks" listing page to display a list of all the trucks with a description and data that comes from the metadata stored in a https://github.com/Netcentric/vg-macktrucks-com-rd/issues/102 allowing the users to navigate through the different segments I've classified my trucks in in a tabbed filter manner.
**Description**
Create a New block that allows user's to navigate and filter the trucks based on the segments. 
**Acceptance Criteria**
1. A new block "Filter Trucks" is available for the content editors to use that displays:

- A tabbed filter with all trucks and all available segments (All trucks, electric, highway, medium duty, vocational and refuse).
2. As a user I can navigate through the different tabs and depending which tab I select, a different set of trucks appears.
3. On mobile the Filtering works as an in-page navigation.
4. 4. The style of the filter corresponds to the design in[ figma. ](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2231-55247&mode=dev)

**Comment by DanielaPedrochevd** [comment]
Has to go after #102 and before #55

**Comment by DanielaPedrochevd** [comment]
This functionality is also needed in #70 (the Header)

**Comment by Andrei-Boiangiu** [comment]
confirmed as done 
 as tested on https://55-all-trucks-listing--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/marko/v2/all-trucks
