### ISSUE TITLE
FR: MT Hero V2 Block displays different images for mobile and desktop. 

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#106]
**Agile requirement** 
As a business owner, I want to display a different image resolution for Mobile and Desktop so that I can achieve the following look: 

![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/144998505/e48cddc6-3ee8-49dd-8655-67717fe55e3d)

**Description** 
Allow Hero V2 block to display different (previously uploaded images) for the different viewports (mobile, tablet? and desktop) a solution similar to the one on the Trucks lineup block.

 
**Acceptance Criteria**
1- As an editor, I'm able to set an image for desktop, mobile, and tablet? viewports just like it is done with Volvo. 
2- The Hero V2 block is always in 100% view in all of the browsers; see https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/175

**Comment by BeckyMedlin** [comment]
Per @WendyKruger: Please adjust the code as was done for Volvo. Ideally I’d like the ability to specify a desktop, tablet, and mobile image.

**Comment by BeckyMedlin** [comment]
@WendyKruger @cogniSyb needs a portrait picture with a 2/3 ratio of at least 750px wide and a landscape image of 16/9 of at least 2000px wide. He has some screenshots that he will share later to show the outcome with the current hero images for the homepage. The hero images need to be provided for the PDPs as well (edited)

**Comment by WendyKruger** [comment]
@cogniSyb @BeckyMedlin Here are the images for the home page. Will provide for PDPs next.

![hero-mobile-anthem-group-parked-2a-v1m](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/ab8252e1-1b96-4126-8650-4dcc5e2fadd9)
![hero-desktop-anthem-group-parked-2a-v1m](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/52f25efb-5f2d-4644-9a91-f084299d3a30)

**Comment by WendyKruger** [comment]
Here are the PDP hero images @cogniSyb @BeckyMedlin 
![hero-pdp-mobile-anthem](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/fa8726e7-482f-4e3f-93fe-bbd9a50687a9)
![hero-pdp-mobile-granite](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/0b78f0a0-6671-4a15-beab-9c2d3d6e3d71)
![hero-pdp-mobile-md](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/951c1a80-3adf-496e-a0b1-dbf2690b9a6b)
![hero-pdp-desktop-terrapro](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/00df1f9c-87e3-41e3-b101-5d2d93477bdd)
![hero-pdp-desktop-lre](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/977c048e-32ee-4201-9bd7-3b5b8afbc481)
![hero-pdp-desktop-pinnacle](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/129fa981-d513-4970-9ff6-d4c49cf1c570)
![hero-pdp-desktop-lr](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/1409a7a2-f408-4ee9-a752-a98d316c6fdc)
![hero-pdp-desktop-anthem](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/62ce0a5e-a6a0-4ac2-9a90-661a2c585f36)
![hero-pdp-desktop-granite](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/a9b5734d-78d4-45a9-a070-03495778a008)
![hero-pdp-desktop-md](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/310a4b70-7bb6-444d-8802-2c6206e25eb5)
![hero-pdp-mobile-terrapro](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/7be38f8e-cc47-49d0-a496-a59429a5f17d)
![hero-pdp-mobile-lre](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/19019d26-ea05-4c09-8dac-3c3cc807ed6e)
![hero-pdp-mobile-pinnacle](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/2f0ba13e-3891-4d28-8692-68755c5a13d4)
![hero-pdp-mobile-lr](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/9605af33-ab3e-4674-9f4d-2ca9a5ccd53f)

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
 
 as tested with two images on https://106-hero-adaptive-images--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/syb/hero
 and with one image on https://106-hero-adaptive-images--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/syb/hero1
