### ISSUE TITLE
FR: Pencil Promo block

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#108]
**Agile Requirement** 
As a content editor, I want to link to a specific segment or truck. This link can be displayed with an image background or a colored background (black or copper). 

**Description**
Create a new block that has 4 different variants (pencil banner black, pencil banner copper, promo block copper, promo block gold ) 

The design of these links should look as the following figma design: 

https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2231-57714&mode=dev

https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=480-81876&mode=design&t=ggJvLexXMqb1cGWG-4

The promo block gold is the same as the copper but the square from the arrow is gold instead. 

**Acceptance Criteria**
- The block will be named "Pencil Promo"
- As an editor I can add the new block to any page. 
- As an editor I can select between the four variants (black and copper pencil banners or the promo block copper or gold).
- The new block follows the Figma designs and styling. 
- As an Editor, for the promo block variant, I can add different images for the different viewports (just like for the Mack Trucks hero).
- As a user, I'm able to click on the whole banner and be redirected. 
- As an editor I'm able to add the link where the user will be redirected upon click.

**Comment by DanielaPedrochevd** [comment]
Design Question: there seems to be a difference in the wording on the desktop and mobile versions "Explore Mack Refuse" vs "Explore Refuse".

**Comment by markovukiceviccn** [comment]
@DanielaPedrochevd 

"As an editor I can select between the four variants (black and bronze pencil banners or the promo block bronze or gold).
"

Which way should be used by content editors to choose between these four variants? Block data attributes or block html class names?

**Comment by markovukiceviccn** [comment]
@DanielaPedrochevd @cogniSyb 

In the Agile requirement section above there are **six** links leading to the same **two** figma design files.
I assume this is unintentional.
Please remove these links to avoid confusion and noise.
Also remove this line since the statement is implied in the sole meaning of this Agile requirement.
"The new block follows the Figma designs and styling."

**Comment by markovukiceviccn** [comment]
@DanielaPedrochevd 
Any remark about Pencil banner link's hover states, is there any change or animation happening?

**Comment by markovukiceviccn** [comment]
@DanielaPedrochevd 
> As an Editor, for the promo block variant, I can add different images for the different viewports (just like for the Mack Trucks header)

Here, I think you meant Mack Truck Hero instead of Mack Truck Header?

**Comment by DanielaPedrochevd** [comment]
Hello Marko, I deleted the extra links from the ticket and edited the wording accordingly. I won't delete acceptance criteria from about design and style for testing purposes. 

Also, I'll ask Wendy again about the hover effects. 

Regarding selecting between variants, please follow the same approach as with the rest of the blocks with different variants.

**Comment by BeckyMedlin** [comment]
@WendyKruger Please see questions above and advise. Thanks!

**Comment by WendyKruger** [comment]
> @DanielaPedrochevd Any remark about Pencil banner link's hover states, is there any change or animation happening?

@DanielaPedrochevd please use the same hover effect as on all other links/buttons.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, issue could be closed 

Test URLs:  https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/marko/v2/all-trucks
sidekick : https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-pencil-promo&index=0

<img width="1792" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/125972657/b67a9392-6d48-48b9-89bb-df551f6cb691">
