### ISSUE TITLE
Bug - Critical - Tabbed carousel multiple instances get combined

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#109]
When trying to add two tabbed carousels below each other, they get combined into one, and content breaks. See https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/pdp

Result:
![Frame 2609240](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/133873665/5a72b49c-193d-4ca4-a84f-6fb4b3a1ea50)

Expected outcome:
![Frame 2609241](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/133873665/db3b2dde-afc1-42ea-926f-85822bb9938c)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
as tested on https://109-tabbed-carousel-instances--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/lakshmi/v2/tabbed-carousel
