### ISSUE TITLE
Testimonial

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#11]
New component for homepage and other pages

Variants:
- [with video](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2244-171462&mode=design&t=Ui58kA2zbVJpDxoC-4) vs. [only image](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-159054&mode=design&t=Ui58kA2zbVJpDxoC-4)
- media right vs. [media left](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2232-60938&mode=design&t=Ui58kA2zbVJpDxoC-4), on mobile the image will be shown first
- overlap vs. no overlap

With video: footer will be added to contain author. When there’s too much content, the [author text will overflow](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-99518&mode=design&t=Ui58kA2zbVJpDxoC-4). Play button added in this footer. 

The play button will open a modal window with the video.

![Image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/133873665/11a078b9-b9a4-4568-abcb-9f0382a26433)

**Comment by Andrei-Boiangiu** [comment]
circling this back to In Progress for the topic of the text being shown first on [Mobile view for Testimonial blocks with media on the left](https://github.com/Netcentric/vg-macktrucks-com-rd/issues/53)

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
