### ISSUE TITLE
Card Row Block

### ISSUE THREAD

**Issue by Gonzalo-CG** [Netcentric/vg-macktrucks-com-rd#112]
**Agile Requirement**
As a business owner, I want to display content so that it follows these designs, to achieve a more dynamic site: 

- [4 Cards Row](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=478-32530&mode=dev)
- [2 Cards](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=478-32530&mode=dev)
- [3 Product Cards](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=478-32530&mode=dev)

**Description**
Create a Card Row Block with three variants (4 Cards Row, 2 Cards and 3 Product Cards) following the design in figma.
To do so, 4 cards row is quite different to any block already available in the current sidekick library. 2 Cards is very similar to the current Cards block but we would need to add the bold font as well as changing the "Explore" button to a slightly bigger one. The 3 Product Cards variant should also contain content in a text list form and the cards on Mobile view should be scrollable. 

**Acceptance Criteria**
1. As an editor, I can add a new "Card Row" block to any page. 
2. As an editor, I can add links to these card so that users are redirected to them upon click. 
3. As an editor, I can select any of the three available variants for this block (4 Cards Row, 2 Cards and 3 Product Cards). 
4. The different available variants follow the style and design in figma: 

- [4 Cards Row](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=478-32530&mode=dev)
- [2 Cards](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=478-32530&mode=dev)
- [3 Product Cards](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=478-32530&mode=dev)

**Comment by DanielaPedrochevd** [comment]
Will be solved separately in #187  #189 and #188
