### ISSUE TITLE
FR: Icon cards

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#119]
**Agile Requirement**
As a user, I want to be able to check interesting information about a truck in a visual, easy way so that I can be more informed when making a purchase. 

**Description**
There is already some work done which makes this [design](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=480-87431&mode=design&t=ap1xP2H1pO6MtOyx-4) achievable, https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/syb/columns however we would separate this "V2 Columns info" into its own block and make it so that if editors add a 4th column, it has a gold background and editors can add a video to be played. This should be done the same as in the [Testimonial block](https://github.com/Netcentric/vg-macktrucks-com-rd/issues/11).

**Acceptance Criteria**

1. There is a new "Icon Cards" block that editors can add to any page. 
2. The block is composed by: 

- A section composed by up to 4 cards (three with white background and if editors add a 4th one it will have a gold background). 
- The Header and background image come from the section metadata, so they are handled separately. 

3. The block follows the design and style in[ figma. ](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=480-87431&mode=design&t=ap1xP2H1pO6MtOyx-4)
4. On desktop the cards are displayed horizontally but on mobile and tablet, they are displayed vertically. 
5. The last card (with the gold background) has a link to a video.

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
