### ISSUE TITLE
FR: MT Resources block 

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#126]
**Agile Requirement**
As a business owner, I want to display information about resources and manuals to allow users to take optimum care of their trucks.

**Description** 
Create a new block where editors can add a title and 2 text sections that include each: 
- A subtitle 
- Text
- A link

Edit the already available [grid design on the homepage](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2220-93083&mode=dev) (within the section level) to have a new variant that follows the design [of the solutions page (the dotted pattern). ](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101626&mode=dev)

Edit the background color shades available in the section level to add a new shade of grey (name to be decided). 

This content has to be displayed as in the design: 
https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101620&mode=dev

**Acceptance Criteria**

-As an editor, I can add this new block to any page. 
-As an editor, I can select a new grey shade of color (name to be decided). 
-As an editor, I can add the new variant of the grid to the section. 
-As an editor, I can configure this bnew block by adding a title and two sections of text. Each of these contains: 
- A subtitle 
- Text
- A link

-As an editor, when I have correctly configured this block, it is displayed following the design. 
[- Mobile
](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-102323&mode=dev)[- Desktop](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101621&mode=dev)
- Tablet design follows the mobile solution.

**Comment by girishdigrajkar** [comment]
Validated and below are the observations :

Desktop: 
1. Block’s actual size is 1440px X 306px (without padding) whereas, expected size is 1440px X 298px (without padding )   - 
2. Background with dots section has pixel size as 248px X 195.88px whereas, expected size is 246px X 246px -

**Comment by girishdigrajkar** [comment]
Based on below response for outstanding observations reported & validation results marking this ticket to done status as no more issues exists.

[Santiago Homps]
1. additional text was added in order to test multiline block
2. the dots get cut on the bottom of the block and in figma this is not considered.
