### ISSUE TITLE
Trucks lineup carousel (MVP)

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#13]
MVP: We’ll copy the code of https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/16 and style it to fit into the Mack styling. Design will happen in the browser.

The navigation tabs will be positioned above the carousel images.

[Design](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2220%3A92927&mode=dev)

To be done after [#36](https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/36)

**Comment by DanielaPedrochevd** [comment]
@kesiah Can you please assign this ticket to @Andrei-Boiangiu if it is ready for testing? Thanks :)

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
 with the mention of the two minor Bugs above and a slightly different rounded pixel size value of the Explore buttons

**Comment by WendyKruger** [comment]
@cogniSyb didn't we talk about Mack having the ability to use a different image for mobile in this block? I see the min-width code implemented on VTNA's version, but not on ours. 

![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/0bc83f4f-5466-4d6b-9ea2-f045b225327f)
![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/2efca796-93cf-42a8-a4ed-b102f4fe763a)

**Comment by cogniSyb** [comment]
@WendyKruger indeed, we talked about it in one of the design meetings. It was confirmed that the same image was expected on mobile/tablet. Changing this would mean implementing some adjustments.

**Comment by WendyKruger** [comment]
> @WendyKruger indeed, we talked about it in one of the design meetings. It was confirmed that the same image was expected on mobile/tablet. Changing this would mean implementing some adjustments.

Let's definitely do this.
