### ISSUE TITLE
Section Metadata: Horizontal Separator

### ISSUE THREAD

**Issue by Gonzalo-CG** [Netcentric/vg-macktrucks-com-rd#130]
### Description
A horizontal separator line is used in several places throughout the [Bulldog Magazine](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2210%3A65358&mode=dev) design. (e.g. [here](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2222-50893&mode=dev) and [here](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2222-53298&mode=dev))

In order to achieve this in Franklin, a new Style called "horizontal separator top" will be added to the Section Metadata block.

Horizontal line design:
<img src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/139977780/b0bb3266-2297-4963-a41d-7dba7dd0ebca" width="100%">

### Acceptance Criteria

- [ ] The "horizontal separator top" Style is available for authors to add on any Section Metadata Block.
- [ ] The horizontal line added at the top of a section by the "horizontal separator top" Style follows the Desktop and mobile designs in Figma.

**Comment by Gonzalo-CG** [comment]
This will be implemented in #117

**Comment by Andrei-Boiangiu** [comment]
will be covered with #117
