### ISSUE TITLE
FR: MT Solutions Secondary PDP MT8 Hero variant

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#138]
**Agile Requirement**
Create a new Hero variant for the secondary PDP MT8 page -> https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-137825&mode=dev

**Comment by DanielaPedrochevd** [comment]
We should use the PDP hero, no need for a new one, the team sees no value.

**Comment by cogniSyb** [comment]
Duplicate of #42
