### ISSUE TITLE
Media with Content block

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#140]
**Agile Requirement**
As a business owner, I want to be able to display an media with some text that can be followed by icons so that I can display important information about tecnical details of the engines.  

**Description** 
Create a Media with Content block so that an editor can add an image or video, text and 2 icons (optionally) with text as in the[ figma design. ](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=478-71521&mode=design&t=iL9idKrdD26rsMej-4)

This variant is displayed in the [solutions (secondary pdp) page ](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-137856&mode=dev).

**Acceptance Criteria**
1- As an editor, I can add the new block to any page. 
2- As an editor, If I put the image first in the word document it will be displayed to the left and if it's positioned second, then it will be displayed to the right. 
3- As an editor, to configure this block I can add a video or an image, a header and some descriptive text. Optionally I can also use up 2 images as "icons" to imitate the figma design. 
4- As an editor, it is my responsibility to add 2 icons in case I add any and the text related to these images is part of the image. 
5- As a user, when I click on a video, the video modal is opened and the video is reproduced in it.

**Comment by DanielaPedrochevd** [comment]
@WendyKruger would this video be played inline or would it display a modal?

**Comment by BeckyMedlin** [comment]
@SantiagoHomps-NC Are you actively working on this one? If so, it needs to be moved into the current sprint @shirin27

**Comment by girishdigrajkar** [comment]
Observations raised in defect 216 are closed now and hence, this ticket could be closed as block is as expected.
