### ISSUE TITLE
FR: MT Solutions Link List Block 

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#143]
**Agile Requirement**

As a business owner, I want to have a block available for content editors to display as in the [design ](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101584&mode=dev) a set of three columns that contain informative texts followed by links. 

**Description**
Edit the #119 icon cards block to allow editors to display links in cta text instead of buttons to achieve the [design. ](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101597&mode=dev)

**Acceptance Criteria**
1 - As an editor, when I use the icon card block, I can add a cta link instead of a button. 
2 - The design follows the figma specifications: 

- [Mobile](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-102308&mode=dev)

- [Desktop](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101604&mode=dev)

- Tablet

**Comment by DanielaPedrochevd** [comment]
Create 2 issues: 

1- New variant of v2 columns info 
2- Image text and button New variant

**Comment by WendyKruger** [comment]
> close and Create 2 issues:
> 
> 1- New variant of v2 columns info 1sp -> #146 2- Image text and button New variant 3sp -> #145

@DanielaPedrochevd @BeckyMedlin shouldn't this be closed per this comment?

**Comment by DanielaPedrochevd** [comment]
Closed because we will be using what we already have available in our library
