### ISSUE TITLE
FR: MT Image text and button New variant

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#145]
Agile Requirement

As a business owner, I want to have a block available for content editors to display as in the [design ](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101584&mode=dev)a button cta so that users can buy Mack as well as three other links of technical information to gain more knowledge on why to buy Mack. This ticket is for the "teaser" part.

**Comment by WendyKruger** [comment]
@DanielaPedrochevd please split this into two different blocks, I can see a value in being able to use them independently

![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/a1c90279-7fb5-45ad-b3ee-451611ea92dd)

![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/9d9935df-f858-4c17-88ae-76562fe54635)

**Comment by DanielaPedrochevd** [comment]
@WendyKruger This ticket would be for the teaser part (block 1) and #146 for the cards part (block 2) we can see whether we develop new blocks or new variants on existing blocks during refinement.

**Comment by DanielaPedrochevd** [comment]
will be solved in #143 and #146

**Comment by WendyKruger** [comment]
**@DanielaPedrochevd @BeckyMedlin I'm very confused about this as well as #143 and #146. 🙃 

**I was under the impression that ticket 143 was split into this ticket (145) for the half-height hero and 146 for the three-card row with icons.****

> @DanielaPedrochevd which part of the component is the "teaser" and which is the ["cards" part from issue 146?](https://github.com/Netcentric/vg-macktrucks-com-rd/issues/146) Also, I want to make sure they are being developed as two SEPARATE blocks as I can see a value in being able to use them independently.
> 
> Block 1 ![image](https://private-user-images.githubusercontent.com/134631810/289240411-a1c90279-7fb5-45ad-b3ee-451611ea92dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDU2NTcsIm5iZiI6MTcwNjE0NTM1NywicGF0aCI6Ii8xMzQ2MzE4MTAvMjg5MjQwNDExLWExYzkwMjc5LTdmYjUtNDVhZC1iM2VlLTQ1MTYxMWVhOTJkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQwMTE1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGZkYzhhODVhYzMwM2RlMWY1ZWRjZmJjOTcwM2M4YmJlNTlhOTRmMWM2M2M1Y2M3NzM4NTg1MTU2YTE3ZTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p8yqnyx4gumz8fBlZArHtPPlztqZPRESOQRPr5a7cBI)
> 
> Block 2 ![image](https://private-user-images.githubusercontent.com/134631810/289240446-9d9935df-f858-4c17-88ae-76562fe54635.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDU2NTcsIm5iZiI6MTcwNjE0NTM1NywicGF0aCI6Ii8xMzQ2MzE4MTAvMjg5MjQwNDQ2LTlkOTkzNWRmLWY4NTgtNGMxNy04OGFlLTc2NTYyZmU1NDYzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQwMTE1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDI2NDUxMzAzOGI3MjUzODU4ZDc0NjgzZDc1OGI5NWMyMTU1ZGIxYTQ3NDk2NzY0ZThiZTUyYmRjZGM3NzhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fm4u4kZG6I2d5P2Jk0gxRa4AuWUIgrVB4dh8RH47tBU)



> @WendyKruger This ticket would be for the teaser part (block 1) and #146 for the cards part (block 2) we can see whether we develop new blocks or new variants on existing blocks during refinement.



But... then this today...


> will be solved in #143 and #146


**..yet issue 143 is marked as closed? please confirm which two issues correspond to the two parts above.**
