### ISSUE TITLE
FR: MT Powertrain V2 Slider Block

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#147]
**Agile requirement**
As a content editor, I want to be able to add a block that contains an image, a title, and a button with a white or grey background to achieve the design. 

**Description**
Develop a block with two variants. 

- 1 Variant that contains an image, a title (GT America Font Family), and a button.
- The other variant should contain 2 images overlapped displayed with a slider through the middle, descriptive text added by the content editor, model name added by the content editor related to the images, and a title.

The design follows these figma files:

1. https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=9765-36723&mode=dev
2. [(https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=9765-34287&mode=design) -> First Variant](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=9765-34287&mode=dev)

The different background colors will be handled by the sections.

**Acceptance criteria**

- As a content editor, I can add the new block to any page. I can add:
  - Title
  - Description text (optional)
  - Image
  - Second image (optional)
  - Model name text associated to the images (optional)
  - Link of a button (optional)
- On mobile, [the image will be as wide as the viewport](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=9765-36780&mode=dev). On desktop, [it will be as wide as the content wrapper](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=9765-36728&mode=dev) (1040px)
- On desktop, the description text would be aligned at the same height as the heading, on the right. The alignment and sizing needs to be the same as done in #190
- For the comparison variant, [the model names would take maximum 50%](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=9765-34384&mode=dev) of the width and would be aligned to either corner of the wrapper. If the content is too long, it will wrap.
- For the comparison variant, as a user, I can compare both images using the above-mentioned slider dragging it left or right. 

**Solution Direction**
https://cloudfour.com/thinks/building-an-accessible-image-comparison-web-component/

**Comment by DanielaPedrochevd** [comment]
The figma file https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2220-82436&mode=dev contains extra text that is not displayed in the block's desktop version. We consider this a design discrepancy and will go for the desktop design , the mobile viewport design should be the same (no extra description text).

**Comment by DanielaPedrochevd** [comment]
@WendyKruger @HaycockJill As it is very complex to achieve the "comparison slider functionality" within a section of the Mack Trucks Features block #191 Would you agree we add said slider to this block instead to achieve the comparison look?

**Comment by WendyKruger** [comment]
> @WendyKruger @HaycockJill As it is very complex to achieve the "comparison slider functionality" within a section of the Mack Trucks Features block #191 Would you agree we add said slider to this block instead to achieve the comparison look?

I'm open to seeing what that would look like.

**Comment by WendyKruger** [comment]
> @WendyKruger @HaycockJill The figma file https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2220-82436&mode=dev contains extra text that is not displayed in the block's desktop version. We consider this a design discrepancy and will go for the desktop design, the mobile viewport design should be the same (no extra description text).
> 
> ![Image](https://private-user-images.githubusercontent.com/144998505/291579377-0c2d6ebb-e249-411c-beca-86912ee138f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDk1NjEsIm5iZiI6MTcwMzAwOTI2MSwicGF0aCI6Ii8xNDQ5OTg1MDUvMjkxNTc5Mzc3LTBjMmQ2ZWJiLWUyNDktNDExYy1iZWNhLTg2OTEyZWUxMzhmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxODA3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTk3MmFmOTYxYjRiOTBmNTEyNThiZDI1YjAzOWE4ZDc4NTNkZTFjZDJhMmU1YThiNTY1Y2QwMzc3ZDYyNTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gUUn4SsAcrsSdtqMl-sfsRlIpHDEnmo6L4ChZBZZbK4)

Yes, definitely a design error. Not sure why that text is in there to be honest. But... would we be able to have the option for text in both the desktop and mobile? Ok to make this an enhancement if needed.

**Comment by markovukiceviccn** [comment]
@DanielaPedrochevd 
I assume we should use responsive images here like in Hero block?

**Comment by DanielaPedrochevd** [comment]
Yes, please

**Comment by markovukiceviccn** [comment]
@DanielaPedrochevd 
May you show me the image resources for responsive images?

**Comment by DanielaPedrochevd** [comment]
@WendyKruger Can you support Marko on the above comment?

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct result and hence, marking the issue to done status 

**Summary:**
1. Block sizing was observed incorrect however, then got clarification to use revised one from Syb;  Sizing is correct
https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=9765-36808&mode=design&t=L5N2r8ysKPH60h3Q-4
2. Mobile / Tablet viewport looks correct except  Ipad 8 +chrome  shows distorted slider:   [SB] This is unsupported iOS 14 hence, this issue is not considered.
