### ISSUE TITLE
FR: MT Truck Feature Variant (2 Images and Tab)

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#148]
**Agile Requirement**

Create a block variant that allows editors to add the following design to any page -> https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-162475&mode=dev. 

![Image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/144998505/5673904f-43cb-46fc-a08b-594ab4368fdb)

Images change when we change of tab.

**Comment by BeckyMedlin** [comment]
@WendyKruger @cogniSyb needs more info on what kind of images are required. He's not sure how feasible the realisation of  alignment of text and images is (when considering a scalable interface)

**Comment by DanielaPedrochevd** [comment]
As per Design agency meetin on 22/11/2023. This issue won't be fixed as we have decided to go with a design that only contains 1 image and that is already available in our existing block library.

**Comment by WendyKruger** [comment]
@Andrei-Boiangiu @DanielaPedrochevd @cogniSyb @BeckyMedlin 

I just want to make sure we are still able to position an **accordion (outlined in red)** in the bottom corner of the **combined image (outlined in green)** with the existing block **AND** have the **image and text change out when scrolling** just like in #147 

![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/c07836aa-da53-4dc4-b306-912745655dd0)
