### ISSUE TITLE
Bug - Minor - Dealer Locator alignment with new header incorrect

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#157]
With the new header, we need to fix the alignment of the Dealer Locator.

Related to https://github.com/hlxsites/vg-volvotrucks-us/issues/488 and https://github.com/hlxsites/vg-macktrucks-com/issues/500

**Comment by Andrei-Boiangiu** [comment]
The Google logo is hidden behind the sidebar the only way see it is to collapse the sidebar
 Reopening for discussing solution
 cc @cogniSyb
 
<img width="1645" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/5692859f-16a7-4501-ad85-b31e1cbadb93">

<img width="1645" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/fff45044-341a-4b50-b955-0823e4670649">

**Comment by DanielaPedrochevd** [comment]
closed. Will be solved in Franklin https://github.com/hlxsites/vg-macktrucks-com/issues/553

**Comment by DanielaPedrochevd** [comment]
closed. Will be solved in Franklin https://github.com/hlxsites/vg-macktrucks-com/issues/553
