### ISSUE TITLE
Tabbed Carousel variant for wheelbase

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#190]
**Agile Requirement**

As a user, I want to be able to see how the different wheels look on the MD Series Truck in an easy user friendly way. 

**Description**
Create a new variant of the Tabbed Carousel block (#25) where the the user can see different wheelbase options as in the [following design: ](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=9765-29955&mode=dev)

**Acceptance Criteria**

1. There is a new variant available for Tabbed Carousel to add to any page by content editors.
2. The block follows the above mentioned design and style.
    - Minimum width of tabs should be less, so that on desktop we can show all 8 items
    - Instead of motion left to right, we have a fade in/fade out effect
    - Text below header on mobile, top right on desktop. The alignment and sizing needs to be the same as done in #147 
3. The background colour doesn’t have to be changed

**Comment by DanielaPedrochevd** [comment]
Design question: The user experience for mobile as it is displayed in the figma file is not very user-friendly. We have other places in figma that use the slider for the desktop viewport but in mobile the slider is omitted and substituted for some tabs. We suggest to do the same here.

**Comment by WendyKruger** [comment]
> @HaycockJill @WendyKruger The user experience for mobile as it is displayed in the figma file is not very user-friendly. We have other places in figma that use the slider for the desktop viewport but in mobile the slider is omitted and substituted for some tabs. We suggest to do the same here. The final look would be:
> 
> For desktop, the slider as:
> 
> ![Image](https://private-user-images.githubusercontent.com/144998505/291580319-9b775d3f-81df-4ff0-baa8-6eb63008a330.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDk2NTksIm5iZiI6MTcwMzAwOTM1OSwicGF0aCI6Ii8xNDQ5OTg1MDUvMjkxNTgwMzE5LTliNzc1ZDNmLTgxZGYtNGZmMC1iYWE4LTZlYjYzMDA4YTMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxODA5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjFkYTBiYjI1ODAyMmFmYmIwN2Y4ZjI3YjQ0NDk4MzU3OTBmYWVkZGQ0YmRmY2YzNzlhZjQwZjI2ZjFkY2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LUTHPa13O6zQjwZMlNpaYjtvNbVR-Vp0otLTKWa57FY)
> 
> For mobile, we would do a similar solution as in the trucks configurations block (instead of a slider, we would use tabs):
> 
> ![Image](https://private-user-images.githubusercontent.com/144998505/291580482-6063ae97-d7b6-4ff4-840e-7596f08bbe1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDk2NTksIm5iZiI6MTcwMzAwOTM1OSwicGF0aCI6Ii8xNDQ5OTg1MDUvMjkxNTgwNDgyLTYwNjNhZTk3LWQ3YjYtNGZmNC04NDBlLTc1OTZmMDhiYmUxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxODA5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWZhMjJkNjNiNWM5NGEzYmY3MTBjZDVkY2RjNjVmYmE2ZTFlM2RlNmNkMThiZjNlNDk5MzZkZTg0NjY5NTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GCqFCDTCUHb2fYEWxYw0x2EFRfw5As3Z85pI8k6LDjs)

I'm open to exploring that. But we would need to have room for up to 8 options.

**Comment by DanielaPedrochevd** [comment]
Estimation of this ticket went down because now that the specifications of the mobile version are more clear it is less complex as we have a similar solution for the tabbed carousel block.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, marking the issue to done status.
