### ISSUE TITLE
FR - MT Truck Features slider variant

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#191]
**Agile Requirement**
As a user, I want to interactively check the different particular customizations for the refuse and vocational work configurations, via a slider available in the Truck Features block.  

**Description**
Allow content editors to add two different images in any of the truck features block sections. These two images should be displayed in the publish mode overlapped and the user should be able to slide left and right between each of them to compare the customizations, as in the [design. ](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-146289&mode=dev)

**Acceptance Criteria**

1. As an editor I can upload two images on any of the Truck Features block sections. 
2. If two images have been uploaded by an author in a section of the Truck Features block, on publish, they are displayed overlapped and the user can slide left or right between both to compare them using the slider bar following the above mentioned design and style. 
3. By default, the slider bar is in the center of the images. 

Solution direction: https://cloudfour.com/thinks/building-an-accessible-image-comparison-web-component/

![Image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/144998505/5e2dd572-7fd9-4183-8f76-1fb4ed27db8d)

**Comment by DanielaPedrochevd** [comment]
Adding this functionality to the Truck Features block is quite complicated Front-end-wise, making this easy for content editors is complex. As this is a comparison functionality we suggest having it in a different block such as #147. This will allow us to maintain this functionality but implement it in less time.

**Comment by WendyKruger** [comment]
> @WendyKruger @HaycockJill Adding this functionality to the Truck Features block is quite complicated and finding a user-friendly solution for content editors is too. As this is a comparison functionality that we understand can add value to users, we suggest having it in a different block such as #147. This will allow us to maintain this functionality but implement it in less time. Ticket #147 should be then re-estimated in a 5.

Ok, per comments on #147

**Comment by DanielaPedrochevd** [comment]
will be fixed in #147
