### ISSUE TITLE
Incorrect section background on Redesign pages

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#199]
On redesign pages, the wrong background colour is used for sections marked with "black background"

Expected: Secondary/Graphite #1D1D1D
Result: Primary/Black #000000

See below that there’s a specificity issue in the CSS:
![Screenshot 2024-01-11 at 13 15 36](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/133873665/2d415a4f-cdc7-499a-8f4b-a76ec951a421)

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd Is this a bug? Please add milestone for this ticket.

**Comment by WendyKruger** [comment]
@cogniSyb the section metadata style that gives the graphite background color is **dark-background**

**Comment by cogniSyb** [comment]
Thanks @WendyKruger. Still that means a code change required to fix alignment issues:
<img width="445" alt="Screenshot 2024-02-06 at 15 36 05" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/133873665/9da5500a-ecc7-4da0-9f99-ae7c9985a87e">

The margins are correct for a section with "black background" set. I’ll remove "black background" and will apply the right margins for "dark background"

**Comment by shirin27** [comment]
Kamino cloned this issue to [hlxsites/vg-macktrucks-com](https://github.com/hlxsites/vg-macktrucks-com/issues/622)
