### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by Lakshmishri** [Netcentric/vg-macktrucks-com-rd#2]
Implement Footer based on new designs

https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2220-91298&mode=design&t=Sw8MQiZnJzFv5Abr-0

![Image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/4208604/9701be05-d714-4c75-9f18-f0c433ec91a4)

**Comment by BeckyMedlin** [comment]
@Lakshmishri Is this a bug or an enhancement?

**Comment by Lakshmishri** [comment]
Yes becky,  I think this is duplicate.
