### ISSUE TITLE
Spike: How to Embed Configurators without using an iframe or a sub-domain.

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#206]
**Description**
Find a way to embed configurators such as the MT Configurator without using an iframe or subdomain. The ideal scenario is that the outcome of the spike serves both Volvo and MT. 

The idea is to create a variation of the embed block and to find out where this application will be taken. 

**Outcomes of Mack Redesign | Truck builder integration call on 2/7:** 
- New Page needed: [www.macktrucks.com/trucks/build](https://www.macktrucks.com/trucks/build) or [www.macktrucks.com/trucks/anthem/build](https://www.macktrucks.com/trucks/anthem/build) - need to test and sync on URL structure. 
- Icon in builder to point to this page for users in the configurator
- Old URL will redirect to this page
- We will validate / test in preproduction with the script
- OG tag per configurator page
- Need from Mack Marketing team: image, title and description per truck
- Next session scheduled for follow up on 2/21

**Comment by DanielaPedrochevd** [comment]
We tested the "my assets functionality" in tickets #204 and #330 (Volvo stream) details in the comments of the mentioned tickets.

**Comment by cogniSyb** [comment]
As mentioned before in other meetings, the solution provided by RapidImages doesn’t work well with AEM. We’re breaking some scripting with this solution approach.

The shadow DOM implementation could work as well, but would require some structural changes to the React application.

**Comment by shirin27** [comment]
Kamino cloned this issue to [hlxsites/vg-macktrucks-com](https://github.com/hlxsites/vg-macktrucks-com/issues/579)
