### ISSUE TITLE
FR: Mack Trucks Configurator Embed to website

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-macktrucks-com-rd#209]
Apply lessons learned from Volvo ticket to then deliver the same experience to Mack Trucks. 

Dependance on: https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/199 
https://github.com/hlxsites/vg-macktrucks-com/issues/579

**Comment by shirin27** [comment]
@BeckyMedlin I've transferred the issue to the Mack Trucks repo and added the MT Configurator milestone.

**Comment by BeckyMedlin** [comment]
@shirin27 Below are the updated staging URLs from @WendyKruger:

we're still in a staging environment, and we don't have the main landing page done yet so you have to go to each truck on a separate url. if it helps, here are the links to the three trucks we have in staging as of now:
 
https://mack:),SKlYQ~,powkNX@truckbuilder-mack-100031.onecx.stag.rapidimages.net/#/anthem
 
https://mack:),SKlYQ~,powkNX@truckbuilder-mack-100031.onecx.stag.rapidimages.net/#/granite
 
https://mack:),SKlYQ~,powkNX@truckbuilder-mack-100031.onecx.stag.rapidimages.net/#/md

**Comment by ZoeBeykirch** [comment]
2/21 update - We should be ready with 7 main truck models (Anthem, Granite, Pinnacle, MD, MD Electric, LR, LR Electric, excluding TerraPro) goal to deploy together for public launch by end of Q1. 

Each truck model URL will start with for example - macktrucks.com/trucks./anthem/build, then become: macktrucks.com/trucks/build/#/anthem for sharing or deep linking. 

Up to date Configurator staging link from Rapid Images: https://truckbuilder-mack-100031.onecx.prod.rapidimages.net/
auth_user = 'mack'
auth_pass = 'jkjK8z8LXz21'

Syb has completed #206 and therefore un-blocked this ticket. We will move forward with iframe approach for MVP launch. However, will need a better longer-term solution as iframe is does not allow for tracking how the user interacts with each step of the configurator - which is valuable data the marketing teams want to track items such as which step in the configurator the average user drops off. 

Test dev link: https://200-truck-configurator--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/tdziezyk/v2/v2-iframe

**Comment by shirin27** [comment]
Kamino cloned this issue to [hlxsites/vg-macktrucks-com](https://github.com/hlxsites/vg-macktrucks-com/issues/591)
