### ISSUE TITLE
Alignment issues media with content block

### ISSUE THREAD

**Issue by SantiagoHomps-NC** [Netcentric/vg-macktrucks-com-rd#216]
This issue was created to address all the issues present in testing.

**Comment by girishdigrajkar** [comment]
**Initial observations which led to creation of this defect :**
**Desktop:**
1. Block’s expected height is 526px Whereas, actual height is 565.14px
2. “The next evolution in piston design.”  Title has font size as 32px whereas, as per figma design it should be 28.8px


**Mobile:**
1. Image height expected size is 248px whereas, actual height is 311.63px

**Comment by girishdigrajkar** [comment]
Validated and able to get correct font also as discussed with Dev(Santiago) the images used are not of exact dimensions and with use of correct image its a no defect hence, closing this defect
