### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#23]
Known in the design as [article list](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=478-32160&mode=dev). On the homepage we show three last published articles. Placed just above the footer, it’s already present on the [current website](https://www.macktrucks.com/) as the cards block.

### Requirements
- Full width graphite background ([see secondary palette](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=6-1586&mode=dev))
- Heading with marker above it
- Three cards, containing:
  - Image
  - Heading
  - Text
  - Link with chevron
- On mobile, the cards are placed [below each other](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2229-52655&mode=design&t=VZxUPVg4hvuRQ8ce-4)
- On tablet, we’ll handle the design as on current website: two cards on one line when they fit, with one card below it centred
- On desktop, all cards will be placed [on one line](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2229-52626&mode=dev)

#### Sizing
- All cards have 24px padding
- The gap between cards is 16px
- On desktop, the cards will be justified. Together including spacing they’ll be as wide as the maximum content container (1040px)

**Comment by Andrei-Boiangiu** [comment]
reopening to be discussed with a solution for Major Bug #71  and to be retested once its fixed

**Comment by Andrei-Boiangiu** [comment]
bug moved as Minor and ticket moved as Done until further notice
