### ISSUE TITLE
Tabbed carousel block

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#25]
Similar to Volvo Trucks' [tabbed-carousel block](https://www.volvotrucks.us/trucks/vhd/), this will be a new block for Mack Trucks.

### Requirements
- Full width dark background (graphite colour)
- Section contains headline
- Image with a caption
- Tab controls are placed below the image, with a red indicator for the active
- When the tab controls don’t fit in the viewport, they will be scrollable as in #13* and defined in Volvo Experience System:
> ![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/133873665/d2b9cdf9-947a-402f-b29d-120109a74c50)
> On small screens, if the tabs are wider than screen, the user can side scroll to see all tabs.
- When the tab controls don’t fit in the viewport, they will be scrolled into view when active
- Use scroll-snap ([same as on trucks line-up, on the trucks images](https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/36)), for the tabs

#### Image
- On mobile and tablet, the image is full width
- The image won’t expand the content container (maximum 1040px)
- On mobile and tablet, the caption text will be shown below the image
- On desktop, the image caption text will be shown [above a black/transparent gradient](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-159126&mode=dev) to ensure contrast
- On all platforms, the image caption text will be sized to maximum 572px (55% of the maximum content container)
- On desktop, the image caption text will have a margin-left of 32px and a 16px margin-bottom

**Comment by cogniSyb** [comment]
@cogniSyb to agree with agency: background colour of section.

**Comment by Andrei-Boiangiu** [comment]
marked as done with the minor and minimal mentiones of the Minor bug above and the fact that the bottom-margin of the Image caption text is 15px instead of 16px
