### ISSUE TITLE
In-page navigation block for PDP

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#26]
A redesign of the current subnav block, with an important difference: it links mostly to page fragments. This will be a new block.

### Requirements
- Sections should be given an id in Franklin by content editors
- The sections should be added in the in-page navigation block in Franklin
  - The order of links is necessary
  - Title, like "Powertrain"
  - Link, like "#powertrain"
- Have the possibility to add a small CTA button for authors that links to Request a quote
  - On mobile, the button text will be shortened from "Request a Quote" to "Quote"
 

#### Behaviour
- Clicking a link will scroll the user to the page fragment, utilising smooth scroll
- Upon clicking a link, we will utilise `history.replaceState()`*
- On mobile and tablet, the navigation will be hidden behind a toggle
  - A [custom dropdown](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=478-73543&mode=dev) will be used to allow the user to scroll to a different page fragment
- Block is placed [below the hero](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-158965&mode=dev), and remains sticky on scroll
  - The block will be shown below the header (navigation)
  - Utilising intersection observer, the current section in view will be highlighted with a red border below the item
  - On mobile and tablet, the current section in view will be shown as text for the toggle
  -  When the user navigates or scrolls through the sections, the URL is being replaced.

#### Styling
- The hover and focus state of links will be the same as the active state (red border below the item)
- The focus state of items in the custom dropdown will be the same as the hover state

\* By utilising `history.replaceState()`, we ensure that the browser history doesn't grow. When the user navigates or scrolls through the sections, the URL is being replaced. When the browser back button is used, the user will navigate away from the page, rather than navigating through every section they scrolled past.

### Out of scope

- In page navigation on Blog pages, that is a bit different

**Comment by shirin27** [comment]
Adding an id to the section is already available in section metadata.

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
