### ISSUE TITLE
FR: V2 Truck Builder - MVP

### ISSUE THREAD

**Issue by shirin27** [Netcentric/vg-macktrucks-com-rd#32]
**Proposal**: use the columns component block to render different images based on what the user clicks

https://www.figma.com/file/WsbTpDFPmFjr6K1wTrGYrQ/OX_Mack_Preview_23-04?type=design&node-id=47-20621&mode=design&t=9umLWA25ZBty7tAJ-0

### Requirements
- The section will start with a heading containing a marker
- Content authors can add different images for every type of use combination, and based on what the user selects, that is what will be rendered
- Color selection will be picked up in phase 2, #36 
- Content editors can configure what colours to display (name ~ label and colour code ~ displayed colour)
- Images to be used:
  - https://share.macktrucks.com/mackdist//assets/landing-page-images/LINE-GRA-StandardMixer.png
  - https://share.macktrucks.com/mackdist//assets/landing-page-images/LINE-GRA-BridgeMixer.png
  - https://share.macktrucks.com/mackdist//assets/landing-page-images/LINE-GRA-LiftAxleDump.png
  - https://share.macktrucks.com/mackdist//assets/landing-page-images/LINE-GRA-Dump.png

### Open point
- [ ] Analyse if there are too many images to be uploaded
- [ ] Looks similar to [columns variant promo](https://www.macktrucks.com/buy-mack/) ("Mack Financial Services Makes it Easy")

**Comment by Lakshmishri** [comment]
Does this component be better https://www.macktrucks.com/mack-connect/ ?  (More earning time)

**Comment by BeckyMedlin** [comment]
@WendyKruger @cogniSyb requests the renders of the trucks (one truck model and its variants) for the [Configurations](https://github.com/Netcentric/vg-macktrucks-com-rd/issues/32). The sizing is TBD, but we could consider the same as for Truck Features (1600*1480px)

**Comment by WendyKruger** [comment]
@DanielaPedrochevd why was this taken out of the MT PDP milestone? It isn't related to the configurator.

**Comment by shirin27** [comment]
Kamino cloned this issue to [hlxsites/vg-macktrucks-com](https://github.com/hlxsites/vg-macktrucks-com/issues/578)
