### ISSUE TITLE
FR: Specifications block redesign - MVP

### ISSUE THREAD

**Issue by shirin27** [Netcentric/vg-macktrucks-com-rd#35]
### Requirements
- Create a new block for the specs sections that acts as an accordion in mobile and tablet
- Follow the design
- try to reuse the accordion to do nested accordions (uncertain if we can do that)

https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2220%3A90176&mode=dev

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
