### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#37]
Implement scroll to top button, which was missing in the new design.
Current live button: https://www.macktrucks.com/

![Image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/135319298/a1cbd7a8-e448-4e64-a908-e8a9c3950e60)

#### Existing requirements
- The button should be displayed in a fixed position on the screen
- When clicking the button, the page should smoothly scroll back to the top of the page
- The button should only appear when the user has scrolled down a certain distance from the top of the page
- The button should be hidden when the user is already at the top of the page or when the page content does not exceed the viewport height

#### Design requirements
- Make use of the button design for the [newsletter subscription form in the footer](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2220-93098&mode=dev)
- The arrow would be positioned counter clockwise, pointing upwards
- The button should have a shadow [like on the 360 view slider](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-156546&mode=dev)
- The states of the buttons need to be implemented as on https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=49-4333&mode=design&t=cVDpihR7kqOneqkM-4
- Icon to be used can be found [here](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=1-1893&mode=design&t=CRUgnwWRdzPMjdDo-0)

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
