### ISSUE TITLE
Feature carousel

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#39]
A new [carousel block](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2220-93051&mode=dev), with a text container overlapping an image.

#### Requirements
- Section is full width and has a black background
- On mobile, the image will be shown above the text container
- Both image and text container will maintain a square aspect ratio (see also #41)
- The content in the text container will vertically be centred (see also #41)
- Text container content:
  - Eyebrow/pre-heading
  - Heading
  - Text
  - Primary button (optional)
- On the text container we show the [carousel controls](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2227-49836&mode=dev)
- When the end of the carousel is reached, either button will be disabled
- The carousel controls will follow the [standard states](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=49-4333&mode=design&t=cVDpihR7kqOneqkM-4)
- Scroll-snap will be implemented on mobile, but not on desktop
- When the carousel only has one slide, we hide the arrows

**Comment by cogniSyb** [comment]
@Lakshmishri @manuel-vara I just found a [related block without the carousel functionality](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-164831&mode=dev). How would we deal with this?

**Comment by shirin27** [comment]
That might be a carousel with only one slide.

**Comment by Andrei-Boiangiu** [comment]
confirmed as done

**Comment by WendyKruger** [comment]
Just realized this is not what I expected. I believe the original intent of the design was to have the background image change with the carousel click.
