### ISSUE TITLE
Pre-footer

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#40]
Just like the footer, this block will be present on all pages.

1. [Pre-footer Actions](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2220-92908&mode=design&t=Ui58kA2zbVJpDxoC-4)
2. [Pre-Footer Trucks Callout](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2220-92909&mode=design&t=Ui58kA2zbVJpDxoC-4)

#### Pre-footer Actions
- Three links, with an icon (arrow right) and separated with lines
- Shown in three columns when there’s room, will be justified

#### Pre-Footer Trucks Callout
- Links shown of all
- **To do:** figure out what to do when the links don’t fit
- On mobile acts like an accordion

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
