### ISSUE TITLE
Truck features

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#43]
Highlighting [truck features](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-155098&mode=dev). This component utilises scroll snap to jump from one subject to the other.

- Utilise scroll snap with JavaScript. A demo of how it could work: https://codepen.io/StephenScaff/full/egOedp

### Requirements
- On desktop, image is shown on left or right
- On mobile, the image is always shown between header and text
- Image can change on every state
- Scroll/active element indicator (red line on side of text)
- Header nor text is clickable. The text can contain links
- The height of the block is as tall as the viewport but minus the in-page nav. 

### UX points to clarify

- [x] Agency to provide direction of image usage: https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=5522-21057&mode=dev
- [x] Mobile behaviour for the carousel to be specified (assumption for estimation: scroll in the same direction as desktop - top to bottom)
- [x] Is the height of the block relative to the viewport, or is it fixed?
- [x] The link style is not in line with the core design kit

![Image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/135319298/69c67ab7-160b-4220-95a7-04b966bae887)

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
 as tested on https://43-truck-features--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/tdziezyk/v2/truck-features
