### ISSUE TITLE
Bug - Critical - Mobile view - Homepage: Hero v2 - The image on the Hero component is cropped on Mobile view

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-macktrucks-com-rd#47]
On Mobile view - the Image from the Hero component is cropped and only a central segment of it is displayed

**Steps to reproduce:**

01. Open and see the Mobile design rendition of the Homepage: Hero v2 on figma - see the screenshot in this ticket: https://github.com/Netcentric/vg-macktrucks-com-rd/issues/8
02. Go to https://8-hero-block--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/tdziezyk/v2/hero on Mobile view
03. Notice that the image is displayed as cropped on the Mobile view vs how it is specified to be displayed in the redesign in Figma

**Expected result**
Hero image should be fully displayed in the Mobile view as per redesign specifications - see figma in original ticket
**Actual result**
Hero Image is displayed as cropped on Mobile view

![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/0f181c6e-acc7-412a-b510-8ada1896d9ef)

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd @Gonzalo-CG Is this still needed or is this a duplicate?

**Comment by DanielaPedrochevd** [comment]
This bug will be closed and a FR will be created to solve this issue and close https://github.com/Netcentric/vg-macktrucks-com-rd/issues/8

**Comment by DanielaPedrochevd** [comment]
Solved by #106

**Comment by Andrei-Boiangiu** [comment]
closed as per above comments

**Comment by WendyKruger** [comment]
Please adjust the code as was done for Volvo. Ideally I’d like the ability to specify a desktop, tablet, and mobile image.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
