### ISSUE TITLE
Bug - Major - Mobile view - Testimonial - The text is show first on Mobile view for a Testimonial with video and media left

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-macktrucks-com-rd#53]
Testimonial block with media on the left and with video will have the text displayed first on Mobile view

**Steps to reproduce:**
1. Go to https://11-testimonial-block--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/tdziezyk/v2/testimonial
2. Notice the testimonials with the image / with video on the left
3. Switch to Mobile view the same page
4. Notice that the Testimonial blocks with media on the left have the text displayed first like the ones with media on right

**Expected result**
Media on the left should have the image displayed first on Mobile view
- see figma in original ticket 

**Actual result**
Testimonial with media on the left and with video will also have the text displayed first in Mobile view

<img width="389" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/d9c99b76-bdbc-47a2-b4df-e0834fcef949">

**Comment by Andrei-Boiangiu** [comment]
#11

**Comment by TomaszDziezykNetcentric** [comment]
Hi @Andrei-Boiangiu 
The business decided to always display the text first and then the image on mobile devices, regardless of the order of display on the desktop. Please check the second point in the issue #11  description

**Comment by Andrei-Boiangiu** [comment]
as it was decided we hant to have the image/media always on top on Mobile view for testimonials regardless where it is displayed in the Dekstop view
 
 confirmed as fixed
