### ISSUE TITLE
FR: Columns Info variation

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-macktrucks-com-rd#54]
Variation block - To support different content styling in each column, icons with alignment options and 'red line' on top. CTAs to align with generic ones

Design: 

https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-164763&mode=dev

https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2220-83238&mode=dev

![Image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/125895595/1641e7d0-a633-4187-8593-bd3a31c7c43e)

![Image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/125895595/ec07b6c5-cb54-42a9-8d53-ecd20866fd60)

![Image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/125895595/3f8eb6da-ad3b-4dec-bd2c-073b73003b10)

### Requirements
- Create a variation of the columns block that has the styling in the [design] (Variation name: Columns (info) )(https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2220%3A83239&mode=dev), as follows:
  - possibility to add a column with an H2 and a text, that would show the column in the style of the first column (with a red line on top)
  - Possibility to add additional columns in the style of the second / third column (icon, H5, text, button regular)
  - The columns' order can be switched, to have the heading column in the middle, for example, or no heading column at all, depending on the author's input

### Open questions:
- How many H2 can be added? - responsibility of the authors, in the designs there is never more than 1 atm
- Image as a bg - out of scope for this ticket, handled in a separate one

**Comment by shirin27** [comment]
@ZoeBeykirch these are two different designs, of the same type of block I would say, do we really need both stylings for MVP, or could we keep one for MVP and use it in both cases, and then design a new variation maybe later? Wdyt?

**Comment by shirin27** [comment]
Great, let's go like that!
