### ISSUE TITLE
Finance and Purchase block - horizontal cards

### ISSUE THREAD

**Issue by Lakshmishri** [Netcentric/vg-macktrucks-com-rd#59]
- [Figma design](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2220%3A90281&mode=dev)
- Use V2 [columns block ](https://github.com/Netcentric/vg-macktrucks-com-rd/issues/41), in a new variation V2 Columns (condensed) for example
- In mobile they will be displayed after each other
- Handle the block to have [2 links](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&mode=design&t=CMO9tGyL7S8lcFi0-0)

**NOTE**: To be done after #41 

### UX points to be clarified:

- [ ] Interactive elements on the block are not defined in the [Mack core design kit](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?node-id=43%3A4362&mode=dev); we propose to go for the defined link style, with the arrow icon.

**Comment by BeckyMedlin** [comment]
Per discussion with Joe and Zoe, please move forward with your proposal for now for the interactive elements.

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
as tested on https://59-horizontal-cards--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/syb/cards

with the mention that some of the px values differ slightly from the figma designs as to fit on the page
