### ISSUE TITLE
FR: Section metadata options: background colour & image

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-macktrucks-com-rd#64]
Sections can have a background colour defined. In some cases, a dotted pattern is used as a background image. A content editor should be able to activate this for several components. This issue is related to https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/47

- Use CSS variables to change the colour of the blocks
- Check the existing v2 blocks (aprox. 4 blocks: Hero, columns, testimonial, cards) to solve the issue of having different text backgrounds against different bg colours

**Comment by DanielaPedrochevd** [comment]
**Agile requirement**
As a content editor, I'm able to activate a background color defined, in some cases I can define an imaged with a dotted pattern and the text in the section should look ok. 

**Description**
Use CSS variables to change the colour of the blocks
Check the existing v2 blocks (aprox. 4 blocks: Hero, columns, testimonial, cards) to solve the issue of having different text backgrounds against different bg colours

**Acceptance Criteria**
1. Check the V2 esixting blocks using CSS variables.
2. Check above-mentioned blocks with the different text colours and bg colours of the sections.

**Comment by Andrei-Boiangiu** [comment]
confirmed as done 
 as tested on 
 https://64-section-bg--vg-macktrucks-com-rd--netcentric.hlx.page/homepage
https://64-section-bg--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/laura/pdp
