### ISSUE TITLE
Bug - Minor - Cards - On a screen resolution between 744px and 1040px width, the Cards block will not have any margins

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-macktrucks-com-rd#71]
When the Cards block is displayed on a screen resolution that has the width anywhere between 744px and 1040px (including) - the Cards block will not have any side margins displayed

On a screen width less than 744px - the Cards will be displayed one below the other like on Mobile view
and on a screen width more than 1040px - the side margin is displayed

**Steps to reproduce:**
1. Open https://23-card-block--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/tdziezyk/v2/ and view in a screen resolution with a width between 744px and 1040px
2. Notice that there are no side margins on the Cards block

**Expected result**
Side margins should be displayed on the Cards block

**Actual result**
Side margins are not displayed on the Cards block when the screen width resolution is between 744px and 1040px

<img width="940" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/2f42344b-4b6f-4fc5-aa6e-7fd58540a2d2">

**Comment by Andrei-Boiangiu** [comment]
#23

**Comment by BeckyMedlin** [comment]
What's the cut off point? Maybe 744 and 1040px are ok? This seems to be a minor issue, not a major one.

**Comment by kesiah** [comment]
Going to be solved in: https://github.com/Netcentric/vg-macktrucks-com-rd/pull/93

**Comment by Andrei-Boiangiu** [comment]
closing as per above comment
