### ISSUE TITLE
Homepage: Hero v2 block (Retest after closing 106)

### ISSUE THREAD

**Issue by manuel-vara** [Netcentric/vg-macktrucks-com-rd#8]
<img width="1151" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/116451851/31f62c91-7916-49dc-864b-ca2ef9a4ce0f">
New design Figma dimensions, document in Library including aspect-ratio

Decision for the red stripe: 45×4px on mobile, 65×4px on desktop

**Comment by Andrei-Boiangiu** [comment]
reopening for the issue of the Hero Image not being displayed as according to the example in Mobile View

Bug - Critical - Mobile view - Homepage: Hero v2 - The image on the Hero component is cropped on Mobile view #47
https://github.com/Netcentric/vg-macktrucks-com-rd/issues/47

**Comment by DanielaPedrochevd** [comment]
blocked by #106 once this ticket is solved we can retest this and close it.

**Comment by Andrei-Boiangiu** [comment]
retested and confirmed as done after testing #106
