### ISSUE TITLE
Bug: Medium: Sub-nav not present

### ISSUE THREAD

**Issue by manuel-vara** [Netcentric/vg-macktrucks-com-rd#91]
<img width="1664" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/116451851/0cc1cfb2-8283-46d2-8f25-357a6e3d7c67">
<img width="1663" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/116451851/56010f45-23b3-4043-b4b2-9c7f1447d9b1">

**Comment by manuel-vara** [comment]
@Andrei-Boiangiu

**Comment by DanielaPedrochevd** [comment]
@BeckyMedlin Bug spotted and created, I prioritized it to 2 so that a dev can take it as soon as possible after handling 1st level priorities because this bug blocks the go-live I assume.

**Comment by Andrei-Boiangiu** [comment]
#92

**Comment by Andrei-Boiangiu** [comment]
partially fixed
 Sub navigation is still not present on Trucks page and subpages
 
 https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/trucks/
https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/trucks/anthem/
https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/trucks/anthem/features/
https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/trucks/anthem/inventory/
https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/trucks/anthem/specs/

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
