### ISSUE TITLE
Bug - Minor - Safari browser - Trucks page - First Online Configurator button from Cards CTA block should have some padding below

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-macktrucks-com-rd#96]
The first Online Configurator button for Mack Anthem in the Cards CTA block is stuck to the bottom border - should have some padding

**Steps to reproduce:**
1. Open https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/trucks/ on Safari
2. Notice the Online Configurator button for Mack Anthem

**Expected result**
Online Configurator button should have some padding below

**Actual result**
Online Configurator button is stuck to the bottom border of the section

<img width="1424" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/8ee2771d-765d-4656-887b-c1e42f2a2a7f">

**Comment by ZoeBeykirch** [comment]
This looks resolved on Safari now 

![Image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/125895595/37c5ba6b-d9bd-427d-abf1-482363cfd7a5)
