### ISSUE TITLE
Bug - Minor - Chrome browser - Trucks: Anthem: Specs - Line above the Base Configurations slightly overlaps the Truck image

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-macktrucks-com-rd#97]
On the Trucks: Anthem: Specs page, the line above Base Configurations slightly overlaps the truck image

**Steps to reproduce:**
01. Open https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/trucks/anthem/specs/ on Chrome browser
02. Notice the line overlapping the image

**Expected result**
Line should be just below the image

**Actual result**
The line above Base Configurations slightly overlaps the Truck image

<img width="1516" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/728d6780-ff9a-43db-8293-1e3e9ae1eb1b">

**Comment by Andrei-Boiangiu** [comment]
#92

**Comment by ZoeBeykirch** [comment]
@cogniSyb @DanielaPedrochevd same for this ticket, since it's a bug on the live website can it be moved to the Franklin board

**Comment by Andrei-Boiangiu** [comment]
still present and on Live
 
<img width="1586" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/23399d89-2ce5-4565-befc-1d4c9f7985d0">

**Comment by WendyKruger** [comment]
Please remove this from the redesign board

**Comment by ZoeBeykirch** [comment]
Closing this ticket as we have moved it to the [Production board. ](https://github.com/hlxsites/vg-macktrucks-com/issues/557)
