### ISSUE TITLE
Deployment: Redesign Footer Mack Trucks

### ISSUE THREAD

**Issue by Joesturbo** [Netcentric/vg-macktrucks-com-rd#99]
@manuel-vara When deploying the footer for Mack on Monday Oct. 2 - Please remove the hyperlink for "Brand Partnership" when going live

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG @DanielaPedrochevd Adding to current sprint as it is a dependency for the deployment on Monday, 10/2/23.

**Comment by manuel-vara** [comment]
Done. 
Please review it here and confirm it's ok:
https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/

**Comment by Joesturbo** [comment]
Excellent TY
